spring:
  application:
    name: newsservice
  jpa:
    generate-ddl: true
#    open-in-view: false
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5436}/${DB_NAME:news_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      schema: ${DB_SCHEMA:news_schema}
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS news_schema
      connection-timeout: 10000

server:
  port: ${APP_SERVER_PORT:8080}